### ISSUE TITLE
Formatting for Lesson 5 is different than other lessons

### ISSUE THREAD

**Issue by LisaCBrown** [OpenCDSS/cdss-learn-git#13]
### Formatting for Lesson 5 is different ###

on the web page:
http://learn.openwaterfoundation.org/cdss-learn-git/05-lesson-new-repo/lesson-new-repo/

it appears that the formatting is lost. The lesson has content, but looks different than the other lessons.
 This may be purely aesthetic, or something could be amiss?

**Comment by smalers** [comment]
I'm not seeing an issue.  Maybe it was due to me updating the files?  Please advise if this is still an issue or provide more specific feedback.

**Comment by LisaCBrown** [comment]
It is also now working for me. Going to assume something didn't get fully updated, but now it is running okay!
