### ISSUE TITLE
Broken Link in Lesson 6

### ISSUE THREAD

**Issue by LisaCBrown** [OpenCDSS/cdss-learn-git#14]
### Broken Link in Lesson 6 ###
The link under this bullet point

StateMod .gitignore file

is broken. The page returns a "404" error.

**Comment by smalers** [comment]
The link works for me but it was pointing to .gitattributes instead of .gitignore.  I fixed.  Will have Lisa look at it after I deploy the update.

**Comment by smalers** [comment]
Actually the issue is that Lisa does not have access to the StateMod code repository.  I added her as a read-only collaborator so the link works.  I reworked the text to indicate that the link may not work.  Will have to circle around and change the text later when the repository goes public.

**Comment by LisaCBrown** [comment]
Looks like it is working now. Thanks Steve!
