### ISSUE TITLE
Question about Lesson 7a

### ISSUE THREAD

**Issue by LisaCBrown** [OpenCDSS/cdss-learn-git#15]
### Question about Lesson 7a ###

The text in the lesson under "Add and Edit Files Using Text Editor" implies that a .gitignore and .gitattributes file already exists in the branch of the repository that I created. However, I don't see them in Windows Explorer and they are not listed in my Git Bash sessions (when I use the `ls` command). Should I create theses files in the text editor? Or am I missing something?

**Comment by smalers** [comment]
I will update the text.  I added the .gitignore and .gitattributes files myself by copying from another repository.  So, Lisa should add the files.  Note that creating a new repository on GitHub gives the option of adding a .gitignore file but not .gitattributes.  I will mention this also.

**Comment by smalers** [comment]
I made the changes and deployed the updates to the web.

**Comment by LisaCBrown** [comment]
Sounds great!
